version: '3.8'

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./.env
    container_name: springboot_app
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - "8080:8080"
      - "35729:35729"
      - "5005:5005"
    environment:
      SPRING_APPLICATION_JSON: '{
                      "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
            }'
    depends_on:
      - mongo

  # DB
  mongo:
    image: mongo:5.0.2
    container_name: mongo
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - data:/data


  # Visualize data
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo

volumes:
  data : {}

networks:
  default:
    name: mongodb_network
